site_name: Libredesk Docs
theme:
  name: material
  language: en
  font:
    text: Source Sans Pro
    code: Roboto Mono
    weights: [400, 700]
  direction: ltr
  palette:
    primary: white
    accent: red
  features:
    - navigation.indexes
    - navigation.sections
    - content.code.copy
extra:
  search:
    language: en

markdown_extensions:
  - admonition
  - codehilite
  - toc:
      permalink: true

nav:
  - Introduction: index.md
  - Getting Started:
      - Installation: installation.md
      - Upgrade Guide: upgrade.md
      - Email Templates: templating.md
      - SSO Setup: sso.md
  - Contributions:
      - Developer Setup: developer-setup.md
      - Translate Libredesk: translations.md
